### PR TITLE
chore: upgrade `axios` package to fix security vulnerability

### PR DESCRIPTION
**Pull request by krishnagopinath**

### CODE REVIEW

**Comment by palmerabollo** [comment]
Thanks @krishnagopinath .

I've merged it. What I see on my laptop is that 1 test somehow starts failing using axios 0.18.1. I'd like to fix it before releasing a new version.

```
$ npm test

> node-isbn@1.5.0 test /Users/xxx/node-isbn
> mocha test/spec

  ISBN Resolver API
    using callback
      ✓ should resolve a valid ISBN with Google (41ms)
      ✓ should resolve a valid ISBN with Open Library
      ✓ should resolve a valid ISBN with Worldcat
      ✓ should return an error if no book is found
      ✓ should return an error if external endpoints are not reachable
      ✓ should return an error if external endpoints return a HTTP error
      ✓ should timeout on long connections
      ✓ should invoke providers in order specified
      ✓ should reset providers after completion
      ✓ should override default options
    using promise
      ✓ should resolve a valid ISBN with Google
      ✓ should resolve a valid ISBN with Open Library
      ✓ should resolve a valid ISBN with Worldcat
      ✓ should return an error if no book is found
      ✓ should return an error if external endpoints are not reachable
      ✓ should return an error if external endpoints return a HTTP error
      ✓ should timeout on long connections
      ✓ should invoke providers in order specified
      ✓ should reset providers after completion
      1) should override default options

  ISBN Provider API
    ✓ should use default providers if providers array is empty
    ✓ should return an error if providers is not an array
    ✓ should return an error if invalid providers in list
    ✓ should remove duplicates
    ✓ should set providers as expected
    ✓ should return instance after setting provider


  25 passing (202ms)
  1 failing

  1) ISBN Resolver API
       using promise
         should override default options:
     Error: Nock: No match for request {
  "method": "GET",
  "url": "http://xisbn.worldcat.org/webservices/xid/isbn/isbn?method=getMetadata&fl=*&format=json",
  "headers": {
    "accept": "application/json, text/plain, */*",
    "user-agent": "axios/0.19.2"
  }
}
      at end (node_modules/nock/lib/request_overrider.js:277:17)
      at /Users/xxx/node-isbn/node_modules/nock/lib/request_overrider.js:160:9
      at OverriddenClientRequest.RequestOverrider.req.write (node_modules/nock/lib/request_overrider.js:139:9)
      at OverriddenClientRequest.RequestOverrider.req.end (node_modules/nock/lib/request_overrider.js:156:11)
      at /Users/xxx/node-isbn/node_modules/follow-redirects/index.js:117:20
      at RedirectableRequest.write (node_modules/follow-redirects/index.js:85:7)
      at RedirectableRequest.end (node_modules/follow-redirects/index.js:116:8)
      at dispatchHttpRequest (node_modules/axios/lib/adapters/http.js:276:11)
      at new Promise (<anonymous>)
      at httpAdapter (node_modules/axios/lib/adapters/http.js:21:10)
      at dispatchRequest (node_modules/axios/lib/core/dispatchRequest.js:52:10)
      at process._tickCallback (internal/process/next_tick.js:68:7)
```

**Comment by krishnagopinath** [comment]
Interesting.. for me the tests seem to pass 🤔 

I'm using node12. What version of node are you using?

<details>
  <summary>Test results</summary>
  
  ```
  ➜  node-isbn git:(master) npm test

	> node-isbn@1.5.0 test /Users/xx/repos/node-isbn
	> mocha test/spec
	
	
	
	  ISBN Resolver API
	    using callback
	(node:52294) [DEP0066] DeprecationWarning: OutgoingMessage.prototype._headers is deprecated
	      ✓ should resolve a valid ISBN with Google (44ms)
	      ✓ should resolve a valid ISBN with Open Library
	      ✓ should resolve a valid ISBN with Worldcat
	      ✓ should return an error if no book is found
	      ✓ should return an error if external endpoints are not reachable
	      ✓ should return an error if external endpoints return a HTTP error
	      ✓ should timeout on long connections
	      ✓ should invoke providers in order specified
	      ✓ should reset providers after completion
	      ✓ should override default options
	    using promise
	      ✓ should resolve a valid ISBN with Google
	      ✓ should resolve a valid ISBN with Open Library
	      ✓ should resolve a valid ISBN with Worldcat
	      ✓ should return an error if no book is found
	      ✓ should return an error if external endpoints are not reachable
	      ✓ should return an error if external endpoints return a HTTP error
	      ✓ should timeout on long connections
	      ✓ should invoke providers in order specified
	      ✓ should reset providers after completion
	      ✓ should override default options
	
	  ISBN Provider API
	    ✓ should use default providers if providers array is empty
	    ✓ should return an error if providers is not an array
	    ✓ should return an error if invalid providers in list
	    ✓ should remove duplicates
	    ✓ should set providers as expected
	    ✓ should return instance after setting provider
	
	
	  26 passing (220ms)

**Comment by krishnagopinath** [comment]
The one thing I notice, which I apologize for, is that I accidentally committed the `package-lock.json` file.. I'd probably want to remove that before the next release..

**Comment by krishnagopinath** [comment]
As I'm digging deeper, I'm finding multiple issues with this, pertaining to Node 6.

When I try to run `npm install`, on node v6, `node-gyp` just gives up..

```
➜  node-isbn git:(master) ✗ npm i

> fsevents@2.1.3 install /Users/xx/repos/node-isbn/node_modules/fsevents
> node-gyp rebuild

gyp: binding.gyp not found (cwd: /Users/xx/repos/node-isbn/node_modules/fsevents) while trying to load binding.gyp
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/Users/xx/.nvm/versions/node/v6.17.1/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:305:16)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:219:12)
gyp ERR! System Darwin 19.4.0
gyp ERR! command "/Users/xx/.nvm/versions/node/v6.17.1/bin/node" "/Users/xx/.nvm/versions/node/v6.17.1/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/xx/repos/node-isbn/node_modules/fsevents
gyp ERR! node -v v6.17.1
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok
node-isbn@1.5.0 /Users/xx/repos/node-isbn
├─┬ axios@0.19.2
│ └── follow-redirects@1.5.10
....
│ └── regexp.prototype.flags@1.3.0
├── json-stringify-safe@5.0.1
├── lodash@4.17.15
├── propagate@1.0.0
├── qs@6.9.3
└── semver@5.7.1

npm WARN node-isbn@1.5.0 license should be a valid SPDX license expression
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.1.3 (node_modules/fsevents):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.1.3 install: `node-gyp rebuild`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1
``` 

The `install` command _kinda_ succeeds; but when I then run `npm test`..

```
➜  node-isbn git:(master) ✗ npm test
> node-isbn@1.5.0 test /Users/xx/repos/node-isbn
> mocha test/spec

/Users/xx/repos/node-isbn/node_modules/mocha/lib/cli/run-helpers.js:102
const singleRun = async (mocha, {exit}, fileCollectParams) => {
                        ^

SyntaxError: Unexpected token (
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:549:28)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
    at Module.require (module.js:504:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/xx/repos/node-isbn/node_modules/mocha/lib/cli/options.js:15:16)
npm ERR! Test failed.  See above for more details.
```

At this point, we have some options: 

* Stop supporting node 6 altogether (will have to bump version to 2.x.x)
* Bring down mocha version to when it supported node 6!

What do you think we should do?

**Comment by krishnagopinath** [comment]
@palmerabollo -- So, I chickened out and brought down the mocha version; I also fixed the issue with that broken test: https://github.com/palmerabollo/node-isbn/pull/19

**Comment by palmerabollo** [comment]
Thank you. I also think that releasing a new 2.x.x version deprecating support for node 6 would be fine if that helps us keep the code cleaner/safer.

**Comment by krishnagopinath** [comment]
@palmerabollo I think we can leave this at node 6 for now. We dont use any specific features that later versions of node offer us. I also feel like this lib is very tiny in scope that node version shouldn't matter. 

We could probably just release it as `1.5.1`. 

What do you think?

**Comment by palmerabollo** [comment]
Sure, release 1.5.1 has just ben published with the fix. Thank you !

**Pull request merged**
